server:
  port: 8080

spring:
  profiles:
    include:
      - secret

  jpa:
    hibernate:
      ddl-auto: update   # create update none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  redis:
    host: localhost
    port: 6379

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: chatdb
      # username: 추후에 추가
      # password: 추후에 추가
      # uri: localhost:/chatdb

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.babyak.babyak: debug
