server:
  port: 8080

spring:
  profiles:
    include:
      - secret

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: info
    com.babyak.babyak: debug